//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by GL.RC
//
#define IDC_START                       198
#define IDC_NEXT                        1000
#define IDC_GET_F1                      1106
#define IDC_GET_F2                      1107
#define IDC_GET_FS                      1108
#define IDC_GET_RMODE                   1115
#define IDC_GET_FATTEN                  1116
#define IDC_RADIO8                      1117
#define IDC_RADIO9                      1118
#define IDC_STOP                        1135
#define IDC_PREV                        1135
#define IDC_BEST                        1136
#define IDC_TEST                        1137
#define IDC_CLEAR                       1138
#define IDC_WIN                         1139
#define IDC_DISTANCE                    1141
#define IDC_CLEAR_BUTTON                1142
#define IDC_SAMPLE                      1144
#define IDC_WINDOW                      1149
#define IDC_SCAN_START                  1150
#define IDC_GANT_START                  1151
#define IDC_SCAN_STATE                  1156
#define IDC_COMMAND                     1157
#define IDC_CHECK_START                 1158
#define IDC_CHOOSE                      1162
#define IDC_SAVE                        1163
#define IDC_OUT                         1165
#define IDC_MODE                        1168
#define IDC_SIL                         1172
#define IDC_CLEAR_MODE                  1173
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         135
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
