//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CR.RC
//
#define IDM_GOTO_LOCATE                 103
#define IDR_FSEARCH_MENU                106
#define IDR_LOCATE_MENU                 107
#define IDM_DRIVERTEST                  108
#define IDM_HELP_ABOUT                  110
#define IDM_LOCATEHELP                  111
#define IDR_CHECK_MENU                  111
#define IDM_OPTIONS_MIXER               114
#define IDM_APPABOUT                    115
#define IDM_SEARCHHELP                  116
#define IDM_EXIT                        117
#define IDM_LOC_CLEAR                   118
#define IDM_LOCATE_START                119
#define IDM_LOCATE_STOP                 120
#define IDM_SCAN_START                  121
#define IDM_SCAN_STOP                   122
#define IDM_OPTIONS_COMMAND             124
#define ID_HELP_APPABOUT                126
#define ID_HELP_CHECKHELP               127
#define IDM_CHECK_START                 128
#define IDM_CHECK_STOP                  129
#define IDM_SELECT                      131
#define IDM_COMPARE                     132
#define IDM_WAVE                        133
#define IDM_OPTIONS_SAVE                134
#define IDM_GOTO_SEARCH                 135
#define IDM_CLEAR                       143
#define IDM_GOTO_CHECK                  144
#define IDC_NEXT                        1000
#define IDC_MAN_ID                      1002
#define IDC_PROD_ID                     1004
#define IDC_VERSION                     1006
#define IDC_NAME                        1007
#define IDC_FORMAT                      1008
#define IDC_CHANNEL                     1016
#define IDC_SUPPORT                     1018
#define IDC_CLEAR                       1048
#define IDC_NUM_INP                     1080
#define IDC_NUM_OUT                     1081
#define IDC_DEVICE_CUR                  1082
#define IDC_WIN_TEXT                    1095
#define IDC_WIN_START                   1102
#define IDC_GET_F1                      1106
#define IDC_GET_F2                      1107
#define IDC_GET_FS                      1108
#define IDC_GET_RMODE                   1115
#define IDC_GET_FATTEN                  1116
#define IDC_RADIO8                      1117
#define IDC_RADIO9                      1118
#define IDC_SPEAKER_DIST                1119
#define IDC_COMMAND                     1124
#define IDC_START_SEARCH                1128
#define IDC_START_CHECK                 1129
#define IDC_START_LOCATE                1130
#define IDC_PREV                        1135
#define IDC_BEST                        1136
#define IDC_SELECT_F                    1137
#define IDC_LOC2                        1138
#define IDC_WIN_PICTURE                 1139
#define IDC_START                       1140
#define IDC_DISTANCE                    1141
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         148
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
