//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by GANT.RC
//
#define IDC_OPTIONS                     103
#define IDC_START                       198
#define IDC_CLEAR                       1138
#define IDC_PICTURE                     1175

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         135
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
