//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SCAN.RC
//
#define IDC_GET_F1                      1106
#define IDC_GET_F2                      1107
#define IDC_COMMAND                     1157
#define IDC_NSOUND                      1173
#define IDC_NCIRCLE                     1174
#define IDC_F1_ARR                      1182
#define IDC_F2_ARR                      1183
#define IDC_SOUNDS_ARR                  1184
#define IDC_SCAN_ARR                    1185
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         146
#define _APS_NEXT_CONTROL_VALUE         1186
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
